### PR TITLE
Add tournament listings

### PR DESCRIPTION
**Pull request by Absotively**
Requires running a migration and rebuilding the css. And also `composer dump-autoload`, I think.

### CODE REVIEW

**Comment by Absotively** [comment]
[P1: Add Store Champs page to OP section](https://trello.com/c/CPclDOC9/48-p1-add-store-champs-page-to-op-section)

**Comment by x3N1GM4x** [comment]
"Running a migration" = `php artisan migrate`? Or something else? Cos my local didn't like this after pulling:

image

**Comment by Absotively** [comment]
Wasn't you, I apparently had picked the wrong option for getting the tournament listings into the site menu. Should work now!

**Comment by x3N1GM4x** [comment]
Amazing, working great for me, awesome work!

My super minor, pedantic, nitpicky thoughts:

When entering the reg and start times on a Tournament, can we suppress the "seconds" part of the time? I doubt anyone is gonna be scheduling that accurately! 😝 

Is there scope to steal the expandable section interface we have on the FAQ page and apply it to tournament listings, so the Region and/or State/Province/Country levels become expandable/collapsible? Might help make the full listings a bit easier to navigate when there's more than a few listed.

The Tournament Sets menu label hangs over the edge of the left nav bar in the admin panel:

image

Maybe we just remove the bracketed example text and make sure anyone using this just understands what it is? Open to suggestions (or to just ignore this as it's super minor and only affects us, not visitors).

**Comment by Absotively** [comment]
Changed the time picker format, added the time picker to the edit tournament form, shortened the admin menu text.

The expanding sections might be a good idea, but I think they can go in later as an improvement.

**Comment by x3N1GM4x** [comment]
Just getting together the final pieces to get this deployed to production, including a data load of the SCs we've already had info back for. One of the things we've captured is a link to an event page (ABR, FB or similar) - did we want to include that as a field against each Tournament record and show it on the page somewhere as well?

**Comment by Absotively** [comment]
Added links, removed TO name and TO slack name.

Wasn't sure how we want to handle email address we aren't publishing, so I've both made the email optional in the admin forms and added a boolean/ticky box for whether the email should be published. Emails will only be published if they exist and publish_email is true.

Fixed the time picker, because apparently I had gotten rid of the hours instead of the seconds :woman_facepalming:.

Improved the page title for tournament listing pages.

Still need to get rid of the seconds in the times in the tournament listings.

**Comment by Absotively** [comment]
Time formatting is improved. Plus, the admin forms are no longer broken for times past noon!

I've used 24-hour time because we many of our players are in countries where it's common, and I'm too lazy to change the time format based on the region, and also a lot of store champs start before 1 pm anyways. I could certainly change it to am/pm if we want.

**Comment by x3N1GM4x** [comment]
I pulled this latest version, did a migrate, rebuilt css and did a `composer dump-autoload` again, but if I try to saves changes to a Tournament or view the tournament page for a particular set on the site, I'm getting an `Unknown column 'link' in 'field list'` error.

Looking at the DB itself - it seems the `link` column has not been added to the tournaments table - do I need to do something more than a `php artisan migrate` for this to work?

**Comment by x3N1GM4x** [comment]
Never mind, I just did a fresh migration and seed and all is good now. 👍

**Comment by x3N1GM4x** [comment]
Deployed to production, just data load required now.

**Comment by Absotively** [comment]
Ah, yeah, I rolled the new changes into the existing migration because I didn’t see a long-term benefit to making a second migration. I should have warned you about that, sorry.

**Comment by x3N1GM4x** [comment]
No worries, it's good for me to have to figure things out sometime, they might stick in my brain better that way! 😃

**Pull request merged**
