### PR TITLE
Add byline, date to article detail pages

### PR DESCRIPTION
**Pull request by Absotively**
Will require a css rebuild.

### CODE REVIEW

**Comment by Absotively** [comment]
[P2: Add bylines to nisei.net articles](https://trello.com/c/KWghQlbU/85-p2-add-bylines-to-niseinet-articles)

**Comment by x3N1GM4x** [comment]
Looks good to me, nice one!

**Comment by x3N1GM4x** [comment]
Deployed to production. I had to do a hard refresh in my browser as it seemed to have cached the css I guess, but I presume that's not a problem?

**Comment by Absotively** [comment]
Should be fine, it’s not like it’s broken without the css.

**Comment by x3N1GM4x** [comment]
[P2: Include date on Article pages](https://trello.com/c/w0SbPMlP/72-p2-include-date-on-article-pages)

**Pull request merged**
