### PR TITLE
Possible fix for RSS header image

### PR DESCRIPTION
**Pull request by binarymelon**
For some reason it doesn't appear that the listing image urls work the same between my local and the production.  Is anyone able to test in their dev environment and see if the header images display for blog posts.  If so, could you also verify the urls generated in the RSS feed with this fix?

### CODE REVIEW

**Comment by binarymelon** [comment]
@x3N1GM4x That's odd.  It seems to work on my local.  Not really sure what could be the cause of the error.  I pushed up a possible fix, but it's a complete shot in the dark.

**Comment by x3N1GM4x** [comment]
Hmmm, now the feed loads, but the URL still seems wrong, for example I see:

``

where I expect:

``

so now it's like the root server address is missing (which was present before any changes in this PR were made) and the previously appearing double slash is back as well...

**Comment by binarymelon** [comment]
What does the link to the article look like for you?

**Comment by x3N1GM4x** [comment]
For example:

`<a href="http://192.168.33.10/article/EmergentCreativity201901">Read full article at NISEI.net</a>`

which is a valid/correct link and works fine.

**Comment by x3N1GM4x** [comment]
Looks good, deployed to production. 🎉

**Pull request merged**
